Develop
PanovAlexey/accumulated_points_reward_system pull request #3
Opened 2022-05-30 17:52 UTC by PanovAlexey

2022-06-05 22:52 UTC, Barugoo commented on internal/application/service/luhn/luhnAlgorithmChecker.go
> +package luhn
Здесь описание пакета бы не помешало

2022-06-05 22:52 UTC, Barugoo commented on internal/application/service/luhn/luhn_test.go
> +func Example() {
Я бы разбил этот пример на несколько маленьких

2022-06-05 22:54 UTC, Barugoo requested changes
Комменты гуд, не вижу бенчмарков. Как идея: можно сделать две реализации хранилки метрик на сервере - через массив/линкед-лист и через мапку и сравнить их производительность в бенчмарках на разных операциях. Бенчмарки и разницу профилей сохранить

2022-06-07 08:44 UTC, PanovAlexey commented on internal/application/service/luhn/luhnAlgorithmChecker.go
> +package luhn
Готово, добавил.

2022-06-07 08:44 UTC, PanovAlexey commented on internal/application/service/luhn/luhn_test.go
> +func Example() {
Готово. Сделал два примера.

2022-06-07 08:51 UTC, PanovAlexey commented
> Комменты гуд, не вижу бенчмарков. Как идея: можно сделать две реализации хранилки метрик на сервере - через массив/линкед-лист и через мапку и сравнить их производительность в бенчмарках на разных операциях. Бенчмарки и разницу профилей сохранить

"Хранилки метрик" - это, наверное, что то из проекта DevOps ветки. У меня проект "стандартный". Поэтому, чтобы не покрывать бенчмарками CRUD-ы, протестировал собственные "погрешности".

А бенчмарки были прикреплены двумя файлами "до" и "после".
Вот этот коммит внутри данного МР: https://github.com/PanovAlexey/accumulated_points_reward_system/pull/3/commits/c4c96bc753d458afcff94bdb2bced109684f73ea

Сравнение производил командами:
`
curl -sK -v http://localhost:8081/debug/pprof/heap > profiles/base.pprof
curl -sK -v http://localhost:8081/debug/pprof/heap > profiles/result.pprof
go tool pprof -top -diff_base=profiles/base.pprof    profiles/result.pprof
`

В этом бенчмарке измерялась производительность после удаления забытой строки с `time.Sleep` с самого начала проекта. Удалил эту строку вот в этом коммите данного МР: https://github.com/PanovAlexey/accumulated_points_reward_system/pull/3/commits/de5e8dbcf67c019e336101d54b1229a617f9685b

На случай, если нужны еще функции бенчмарки, добавил сейчас еще один вариант бенчмарка: 
https://github.com/PanovAlexey/accumulated_points_reward_system/pull/3/commits/c6ec739fe8338e21b77f24f88e6d0e5b93d1b0d8
В одной версии алгоритма Луна оставил все как есть, а в другой заменил умножение на битовую логику и вынес создание новой переменной из цикла. Разница оказалась минимальная, что, скорее всего, показывает, что компилятор производит такие очевидные оптимизации самостоятельно.

2022-06-10 07:42 UTC, Barugoo approved these changes
Отлично!

2022-06-10 09:39 UTC, merged